### ISSUE TITLE
Integrate into official SVGR repository

### ISSUE THREAD

**Issue by gregberge** [birdofpreyru/babel-preset-svgr#19]
Hello @birdofpreyru, this project is great! I think it should be part of official SVGR ecosystem. Are you interested to become a core SVGR maintainer and to make this babel-plugin official? As you already know people are looking for that feature.

**Comment by birdofpreyru** [comment]
Hi @gregberge. Promoting this preset to become a part of the official SVGR ecosystem sounds good. Becoming SVGR maintainer, and making extra efforts for that sounds less attractive.

Probably, clarify what do you mean by this at the technical level? From my PoV this preset requires almost no maintenance, beside occasional bumping SVGR versions in `package.json`, and it CI/CD setup does its job, so any extra efforts to move repo / reconfigure CI/CD etc. looks like a waste of time giving no added value. Also SVGR itself just works for me (great job on your side!), and thus it is not that interesting maintaining it, as I never saw any need to change / fix anything in it (beside creating this small preset). Well, maybe upgrading it to SVGO@2 would be great, but I guess you are probably on it already.

**Comment by gregberge** [comment]
If you don't want to be maintainer, it is OK for me. Could you please submit a PR to add this code as a SVGR package. I could copy it but it would be nice for you to have your name in contributors, you deserve it 😉

**Comment by birdofpreyru** [comment]
Can't you keep my name as the author of the package, and add me to the list of SVGR contributors, if you copy the code? :grinning: Not that I am strongly opposing to create PR, but looking at your repo I see that code structure in your packages is different from what I am using here, so I am just not sure what to do with my tests, where to move the readme, and all sorts of stuff which probably will require a lot of back and forth with you to end up with the result you will like, in contrast if you just do it yourself :innocent: Even the name `@svgr/babel-preset`, which would be my first pick for the package within SVGR, is already occupied by another internal sub-package.

**Comment by gregberge** [comment]
> Can't you keep my name as the author of the package, and add me to the list of SVGR contributors, if you copy the code? 😀 Not that I am strongly opposing to create PR, but looking at your repo I see that code structure in your packages is different from what I am using here, so I am just not sure what to do with my tests, where to move the readme, and all sorts of stuff which probably will require a lot of back and forth with you to end up with the result you will like, in contrast if you just do it yourself 😇 Even the name `@svgr/babel-preset`, which would be my first pick for the package within SVGR, is already occupied by another internal sub-package.

OK, good for me!
