### ISSUE TITLE
Base path for "Compatibility with Create React App"

### ISSUE THREAD

**Issue by alvaro-cuesta** [birdofpreyru/babel-preset-svgr#4]
When using CRA compatibility, the original path (default import) is an absolute path, e.g. in my Mac:

`/Users/alvaro/Projects/storybook-static-base/src/assets/icons/alert-circle.svg`

Is there any way to set a base path? So it outputs something like:

`./assets/icons/alert-circle.svg`

I need it for static rendering.

**Comment by birdofpreyru** [comment]
Thanks for suggestion, I added such option in `v1.0.7`.

**Comment by alvaro-cuesta** [comment]
@birdofpreyru wow, that was fast, thanks!

It doesn't seem to work as expected though. In Mac with this configuration in `.babelrc` and using `@babel/node`:

```js
[
  "@dr.pogodin/babel-preset-svgr",
  {
    "mimicCreateReactApp": {
      "pathsRelativeTo": "../../.."
    }
  }
]
```

The output is (see `src` attribute):

```html
<img src="alvaro/Projects/storybook-static-base/src/assets/icons/alert-circle.svg" alt="alert" />
```

No matter what I put in `pathsRelativeTo`, the output is the same.

How can I help you debug this?

**Comment by alvaro-cuesta** [comment]
Nevermind, it was a Babel cache issue. Once run with `BABEL_DISABLE_CACHE=1` it works.

Still not as expected though. For the desired output I had to set options to:

```js
{ mimicCreateReactApp: { pathsRelativeTo: 'src' } }
```

I.e. the `pathsRelativeTo` isn't relative to the preset, but relative to the project source (actually to `cwd`). See Node's `path.relative` docs, which point to `path.resolve`, which says:

> If after processing all given `path` segments an absolute path has not yet been generated, the current working directory is used.

**Comment by birdofpreyru** [comment]
I see. Well, I guess it is even better, as potentially one has more control over the current working directory, rather than over the actual module installation path (which, actually, can be a sub-module of sub-modules in some cases). So, I just need to update README to reflect this.

Also, if you use JS format of Babel config, instead of JSON, the best is just to set the absolute path for this option, like
```js
{ mimicCreateReactApp: { pathsRelativeTo: `${__dirname}/src` } }
```
