### ISSUE TITLE
Feature request: add base URI option

### ISSUE THREAD

**Issue by alvaro-cuesta** [birdofpreyru/babel-preset-svgr#5]
To solve issue #4 a feature was added to change the relative path for CRA-compatible default imports.

The use case is similar to what [`babel-plugin-transform-assets-import-to-string`](https://github.com/yeojz/babel-plugin-transform-assets-import-to-string) supports:

#4 works like `baseDir` in that plugin. Adding something similar to their `baseUri` would allow prepending any string to the path, so we can point to CDNs, other subfolders, the server root `/` (this is what I'd need), etc.

**Comment by birdofpreyru** [comment]
Ok, most probably I'll add it later today. Probably gonna call it `pathsPrefix` though. Feels somewhat more intuitive to me than `baseDir` and `baseUri`.

**Comment by birdofpreyru** [comment]
Released `v1.0.8`. It occured to me, there are diffrent ways somebody may want to add a prefix to generated assset paths, or even to do something else about them, so I ended up adding `pathsTransform` options, which just allows you to provide a custom transform function for paths.
