### ISSUE TITLE
Using a custom .prettierrc breaks mimicCreateReactApp

### ISSUE THREAD

**Issue by alvaro-cuesta** [birdofpreyru/babel-preset-svgr#8]
Pretty much what the title says. As soon as I add my custom `.prettierrc` at the root of my project (see below), the mimic regex fails to match.

Disabling `@svgr/prettier-plugin` also breaks the mimic, so that's not an option either.

I've been unable to disable the custom prettier config _only_ for the prettier plugin (see `.babelrc` below) but I managed to override the `semi` option which was breaking the regex.

Seems fragile though.

- `.babelrc` (excerpt)

    ```json
    [
      "@dr.pogodin/babel-preset-svgr",
      {
        "mimicCreateReactApp": {
          "pathsRelativeTo": "src"
        },
        "svgr": {
          "plugins": ["@svgr/plugin-jsx", "@svgr/plugin-prettier"],
          "prettierConfig": {
            "semi": true
          }
        }
      }
    ]
    ```

- `.prettierrc`

    ```json
    {
      "arrowParens": "avoid",
      "bracketSpacing": true,
      "jsxBracketSameLine": false,
      "printWidth": 80,
      "proseWrap": "preserve",
      "requirePragma": false,
      "semi": false,
      "singleQuote": true,
      "tabWidth": 2,
      "trailingComma": "all",
      "useTabs": false
    }
    ```

**Comment by birdofpreyru** [comment]
@alvaro-cuesta I published **v1.1.1**, which ensures `mimicCreateReactApp` works without `@svgr/plugin-prettier`. I guess, it also fixes the issues with custom `.prettierrc`, though I was not able to reproduce the problem in tests, thus not 100% sure. Please confirm.

**Comment by alvaro-cuesta** [comment]
@birdofpreyru still not working if `@svgr/plugin-prettier` is enabled. Maybe that's why you couldn't reproduce? It needs both the plugin and my custom `.prettierrc` at the project root (or anywhere that Prettier resolves it).

The issue is our `.prettierrc` has `semi: false` so the semicolon in `export default SvgComponent;` is absent and the regex does not match.

Making the semicolon optional in the regex will probably fix the issue, but it seems fragile (What other options might make the `export` differently shaped?)

Not sure what a robust solution would look like though.

**Comment by birdofpreyru** [comment]
OK, **v1.2.0** should be a bullet-proof fix of the problem: now it walks through the actual component AST generated by SVGR, and replaces export statements nodes in the AST, thus making it independent of syntax transformations performed by other plugins.
